name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Don't forget to [Star](https://github.com/Girlscript-WOB/Open-source-Practice) repo & follow me on [GitHub](https://github.com/Durgesh4993) :)"
